### ISSUE TITLE
difficulty running Python 3.7.1 with PSSE 34.7.0

### ISSUE THREAD

**Issue by windcrusader** [danifus/pssepath#2]
Hi team,

Thanks for this tool, it is really helpful. Apologies, if this is more of a technical support question, rather than an issue per se, but I'm not 100% sure it is not an issue.

Anyway, I've been able to use PSSE successfully with pssepath with Python 3.4, but when I recently installed PSSE 34.7.0 to enable support for Python 3.7, I've been unable to get it working. I've installed Python 3.7.1. Below is the output from the tool.

`C:\Users\bradh\AppData\Local\Programs\Python\Python371>python -m pssepath.pssepathinfo
Found the following PSSE versions installed:

  1. PSSE Version 34
      Requires Python2.7-32bit
  2. PSSE Version 34
      Requires Python3.4-32bit
  3. PSSE Version 34
      Requires Python3.7-32bit

Found the following Python installations:
  2.5-32bit:
    PythonCore: C:\Python25\
  2.7-32bit:
    PythonCore: C:\Python27\
  3.4-?bits:
    PythonCore: C:\Users\bradh\AppData\Local\Programs\Python\Python34-4-new\
  3.5-?bits:
    PythonCore: C:\Users\bradh\AppData\Local\Programs\Python\Python35-32\
  3.7-32bit:
    PythonCore: C:\Users\bradh\AppData\Local\Programs\Python\Python371\
    PythonCore: C:\Python37\
  3.9-64bit:
    PythonCore: C:\Users\bradh\AppData\Local\Programs\Python\Python39\
Press Enter to continue...`

So it clearly doesn't pick up the version of Python 3.7.1 which is running as "currently running" even though that is how I launched the script. When I run the following sequence of commands I also get an error:

`Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pssepath
>>> pssepath.select_pssepath()
Please select from the available PSSE installs:

  1. PSSE Version 34
      Requires Python2.7-32bit
  2. PSSE Version 34
      Requires Python3.4-32bit
  3. PSSE Version 34
      Requires Python3.7-32bit
Enter a number from the above PSSE installations: 3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\bradh\AppData\Local\Programs\Python\Python371\lib\site-packages\pssepath\core.py", line 66, in wrapped
    fn(*args, **kwargs)
  File "C:\Users\bradh\AppData\Local\Programs\Python\Python371\lib\site-packages\pssepath\core.py", line 315, in select_pssepath
    check_to_raise_compat_python_error(selected_key)
  File "C:\Users\bradh\AppData\Local\Programs\Python\Python371\lib\site-packages\pssepath\core.py", line 221, in check_to_raise_compat_python_error
    % (req_psse_ver, psse_arch, pyver_text, "-".join(running_py_ver))
pssepath.core.PsseImportError: Current Python and PSSE version incompatible.

PSSE 34 (32bit) requires Python 2.7-32bit or 3.4-32bit or 3.7-32bit to run.
Currently running Python3.7-32-32bit.
`

Any help you give me is much appreciated.

**Comment by danifus** [comment]
Hi,

I think it is an error in pssepath due to differing output of the `sys.winver` attribute in later pythons (32bit python shows as `3.7-32` but we were expecting only `3.7`).

I've pushed out a fix to pypi that alters the way we get the version number so that it should be more consistent across architectures. I don't have access to any psse anymore so I'm relying on others to let me know if this fixes the problem or introduces any backwards incompatibilities.

Please let me know if this fixes your issue or breaks other psse versions

Thanks for the bug report!

**Comment by danifus** [comment]
Fixed by a382d653d5
