### ISSUE TITLE
PSSE 35 registry paths not supported

### ISSUE THREAD

**Issue by theodop** [danifus/pssepath#3]
Hi there,

It looks like the registry path format has changed under PSSE 35 to now include a subfolder for the point version.

For example, for PSSE 35.5:
![image](https://github.com/danifus/pssepath/assets/5206117/e8eb0c63-422a-4f72-9761-93d7598b250b)

**Comment by theodop** [comment]
#4 created

**Comment by danifus** [comment]
Thanks for the PR! Sorry it took a while to get around to merging it.

I don't have access to many PSS/e environments any more so let me know if you run into any issues.
